---
- name: tap external homebrew_cask repositories
  homebrew_tap: tap=caskroom/cask state=present
  become: false

- name: update homebrew_cask
  homebrew: name=brew-cask state=latest
  become: false

- name: install and upgrade homebrew_cask packages
  homebrew_cask: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('present') }}
  with_items: homebrew_cask_packages
  when: homebrew_cask_packages
  become: false
